# Generated by Django 5.1.4 on 2024-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_language_project_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, to='blog.language'),
        ),
    ]
