# Generated by Django 5.1.4 on 2024-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='languages/'),
        ),
    ]
