# Generated by Django 4.2.17 on 2024-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='language',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='languages',
            field=models.ManyToManyField(related_name='skills', to='blog.language'),
        ),
    ]
