# Generated by Django 4.2.17 on 2024-12-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_skill_description_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
    ]
